'use client'

import { useEffect, useMemo, useState } from 'react'
import { apolloClient } from '@/lib/apollo'
import { gql } from '@apollo/client'

const GET_ORGS = gql`query GetOrgs { organizations { id name quota_allowed quota_used workflows { id name workflow_steps { id step_type step_order config } workflow_triggers { id trigger_type } workflow_runs(order_by: {started_at: desc}, limit: 1) { id status started_at } } } }`
const GET_STEP_RUNS = gql`query GetStepRuns($workflow_run_id: uuid!) { step_runs(where: {workflow_run_id: {_eq: $workflow_run_id}}, order_by: {started_at: asc}) { id status output error attempt_count approved_by workflow_step { step_type step_order } } }`
const CREATE_WORKFLOW = gql`mutation CreateWorkflow($name: String!, $org_id: uuid!, $user_id: uuid!) { insert_workflows_one(object: {name: $name, org_id: $org_id, created_by: $user_id}) { id } }`
const ADD_STEP = gql`mutation AddStep($workflow_id: uuid!, $step_type: String!, $step_order: Int!, $config: jsonb!) { insert_workflow_steps_one(object: {workflow_id: $workflow_id, step_type: $step_type, step_order: $step_order, config: $config}) { id } }`
const ADD_TRIGGER = gql`mutation AddTrigger($workflow_id: uuid!, $trigger_type: String!) { insert_workflow_triggers_one(object: {workflow_id: $workflow_id, trigger_type: $trigger_type}) { id } }`

const users = [
  { id: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', name: 'Alice Chen', role: 'owner', org: '11111111-1111-1111-1111-111111111111', initials: 'AC' },
  { id: 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', name: 'Bob Stone', role: 'editor', org: '11111111-1111-1111-1111-111111111111', initials: 'BS' },
  { id: 'cccccccc-cccc-cccc-cccc-cccccccccccc', name: 'Carol Diaz', role: 'viewer', org: '11111111-1111-1111-1111-111111111111', initials: 'CD' },
  { id: 'dddddddd-dddd-dddd-dddd-dddddddddddd', name: 'Dave Okafor', role: 'owner', org: '22222222-2222-2222-2222-222222222222', initials: 'DO' },
]
const stepMeta: Record<string, { label: string; tone: string; icon: string }> = {
  llm_call: { label: 'LLM call', tone: 'violet', icon: 'AI' }, http_request: { label: 'HTTP request', tone: 'blue', icon: 'HTTP' }, conditional_branch: { label: 'Condition', tone: 'amber', icon: '?' }, approval_gate: { label: 'Approval gate', tone: 'rose', icon: 'PAUSE' }, db_write: { label: 'Database write', tone: 'emerald', icon: 'DB' }, notify: { label: 'Notify', tone: 'cyan', icon: 'MSG' },
}

export default function Home() {
  const [orgs, setOrgs] = useState<any[]>([])
  const [userId, setUserId] = useState(users[0].id)
  const [selectedWorkflow, setSelectedWorkflow] = useState<any>(null)
  const [runId, setRunId] = useState<string | null>(null)
  const [stepRuns, setStepRuns] = useState<any[]>([])
  const [name, setName] = useState('')
  const [notice, setNotice] = useState('')
  const [busy, setBusy] = useState(false)
  const user = users.find((item) => item.id === userId) || users[0]
  const org = orgs.find((item) => item.id === user.org)
  const workflows = org?.workflows || []
  const quota = org?.quota_allowed ? Math.min((org.quota_used / org.quota_allowed) * 100, 100) : 0

  async function load() { try { const result = await apolloClient.query({ query: GET_ORGS, fetchPolicy: 'network-only' }); setOrgs((result.data as any).organizations || []) } catch { setNotice('Unable to reach the workflow data plane.') } }
  useEffect(() => { load() }, [])
  useEffect(() => { if (!selectedWorkflow || !workflows.some((item: any) => item.id === selectedWorkflow.id)) setSelectedWorkflow(workflows[0] || null) }, [orgs, userId])
  useEffect(() => { if (!runId) return; const poll = async () => { const result = await apolloClient.query({ query: GET_STEP_RUNS, variables: { workflow_run_id: runId }, fetchPolicy: 'network-only' }); setStepRuns((result.data as any).step_runs || []) }; poll(); const timer = setInterval(poll, 1800); return () => clearInterval(timer) }, [runId])

  async function createWorkflow() {
    if (!name.trim() || !org || user.role === 'viewer') return
    setBusy(true); try { const result = await apolloClient.mutate({ mutation: CREATE_WORKFLOW, variables: { name: name.trim(), org_id: org.id, user_id: user.id } }); const id = (result.data as any).insert_workflows_one.id; const steps = [{ type: 'llm_call', config: { prompt: 'Classify this request as approve or reject.', model: 'llama3-8b-8192' } }, { type: 'http_request', config: { url: 'https://httpbin.org/post', method: 'POST' } }, { type: 'conditional_branch', config: { condition: 'output.action === approve' } }, { type: 'approval_gate', config: { required_role: 'owner' } }, { type: 'db_write', config: { table: 'workflow_runs' } }]; for (const [index, step] of steps.entries()) await apolloClient.mutate({ mutation: ADD_STEP, variables: { workflow_id: id, step_type: step.type, step_order: index + 1, config: step.config } }); for (const trigger of ['manual', 'webhook']) await apolloClient.mutate({ mutation: ADD_TRIGGER, variables: { workflow_id: id, trigger_type: trigger } }); setName(''); setNotice('Workflow created with 5 executable steps.'); await load() } catch (error: any) { setNotice(error.message || 'Workflow creation failed.') } finally { setBusy(false) }
  }
  async function runWorkflow() { if (!selectedWorkflow || user.role === 'viewer') return; setBusy(true); setStepRuns([]); try { const response = await fetch('/api/trigger-workflow', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ workflow_id: selectedWorkflow.id, user_id: user.id, org_id: org.id, role: user.role }) }); const data = await response.json(); if (data.run_id) { setRunId(data.run_id); setNotice('Run started. Progress is updating live.'); } else setNotice(data.error || 'Could not start run.') } catch { setNotice('Run request failed.') } finally { setBusy(false) } }
  async function approve(id: string) { const response = await fetch('/api/approve-step', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ step_run_id: id, user_id: user.id, role: user.role }) }); const data = await response.json(); setNotice(data.success ? 'Approval recorded. Workflow resumed.' : data.error || 'Approval failed.'); }
  const activeRunStatus = stepRuns.some((step) => step.status === 'paused') ? 'paused' : stepRuns.some((step) => step.status === 'running') ? 'running' : stepRuns.length > 0 && stepRuns.every((step) => step.status === 'completed') ? 'completed' : 'pending'
  const selectedSteps = useMemo(() => [...(selectedWorkflow?.workflow_steps || [])].sort((a: any, b: any) => a.step_order - b.step_order), [selectedWorkflow])

  return <main className="min-h-screen bg-background text-foreground"><div className="shell">
    <aside className="sidebar"><div className="brand"><div className="brand-mark">S</div><div><strong>subspace</strong><span>workflow control</span></div></div><div className="side-label">Workspace</div><div className="org-switch"><span className="org-dot" />{org?.name || 'Loading workspace'}<span className="chevron">⌄</span></div><nav><a className="nav-active"><span>◈</span> Workflows <b>{workflows.length}</b></a><a><span>◌</span> Runs <b>12</b></a><a><span>◇</span> Approvals {stepRuns.some((step) => step.status === 'paused') && <i />}</a></nav><div className="side-label team-label">Team context</div><div className="user-list">{users.map((item) => <button key={item.id} onClick={() => setUserId(item.id)} className={item.id === userId ? 'user active' : 'user'}><span className="avatar">{item.initials}</span><span><strong>{item.name}</strong><small>{item.role}</small></span>{item.id === userId && <span className="check">✓</span>}</button>)}</div><div className="sidebar-footer"><span className="status-pulse" /> System operational<br /><small>Hasura + Workflow SDK</small></div></aside>
    <section className="content"><header className="topbar"><div><p className="eyebrow">{org?.name || 'Organization'} / Operations</p><h1>Workflow control room</h1></div><div className="header-actions"><span className="live-chip"><span className="status-pulse" /> Live</span><span className="avatar avatar-large">{user.initials}</span><div><strong>{user.name}</strong><small>{user.role}</small></div></div></header>
      {notice && <div className="notice" role="status">{notice}<button onClick={() => setNotice('')}>×</button></div>}
      <div className="metrics"><div className="metric"><span className="metric-icon violet">◈</span><div><small>Active workflows</small><strong>{workflows.length}</strong></div><em>+2 this week</em></div><div className="metric"><span className="metric-icon blue">↗</span><div><small>Runs this month</small><strong>12</strong></div><em>+18%</em></div><div className="metric quota-card"><span className="metric-icon amber">◷</span><div><small>Monthly quota</small><strong>{org?.quota_used || 0} <small>/ {org?.quota_allowed || 100}</small></strong></div><div className="quota-bar"><span style={{ width: `${quota}%` }} /></div></div></div>
      <div className="workspace-grid"><section className="panel workflows-panel"><div className="panel-heading"><div><p className="eyebrow">Orchestration</p><h2>Your workflows</h2></div>{user.role !== 'viewer' && <div className="create-row"><input value={name} onChange={(event) => setName(event.target.value)} placeholder="New workflow name" /><button className="button primary" disabled={busy || !name.trim()} onClick={createWorkflow}>+ Create</button></div>}</div>{workflows.length === 0 ? <div className="empty">No workflows in this organization yet.</div> : <div className="workflow-list">{workflows.map((workflow: any) => <button key={workflow.id} onClick={() => setSelectedWorkflow(workflow)} className={selectedWorkflow?.id === workflow.id ? 'workflow-row selected' : 'workflow-row'}><span className="workflow-state" /><span className="workflow-copy"><strong>{workflow.name}</strong><small>{workflow.workflow_steps?.length || 0} steps <span>·</span> {workflow.workflow_triggers?.map((t: any) => t.trigger_type).join(' + ')}</small></span><span className={`badge ${workflow.workflow_runs?.[0]?.status || 'draft'}`}>{workflow.workflow_runs?.[0]?.status || 'draft'}</span><span className="row-arrow">›</span></button>)}</div>}</section>
      <section className="panel detail-panel"><div className="panel-heading"><div><p className="eyebrow">Builder</p><h2>{selectedWorkflow?.name || 'Select a workflow'}</h2></div>{selectedWorkflow && user.role !== 'viewer' && <button className="button run" disabled={busy} onClick={runWorkflow}>Run workflow <span>↗</span></button>}</div>{selectedWorkflow ? <><div className="trigger-line"><span className="muted-label">Triggers</span>{selectedWorkflow.workflow_triggers?.map((t: any) => <span className="trigger" key={t.id}><span />{t.trigger_type}</span>)}<button className="add-trigger">+ Add trigger</button></div><div className="step-stack">{selectedSteps.map((step: any, index: number) => { const meta = stepMeta[step.step_type] || stepMeta.notify; const live = stepRuns.find((item) => item.workflow_step?.step_order === step.step_order); return <div className="step-wrap" key={step.id}><div className={`step-card ${live?.status || ''}`}><span className={`step-icon ${meta.tone}`}>{meta.icon}</span><span className="step-index">{String(index + 1).padStart(2, '0')}</span><div className="step-info"><strong>{meta.label}</strong><small>{step.config?.model || step.config?.url || step.config?.required_role || 'Configured action'}</small></div>{live ? <span className={`badge ${live.status}`}>{live.status}{live.attempt_count > 0 ? ` · ${live.attempt_count}x` : ''}</span> : <span className="badge pending">ready</span>}{live?.status === 'paused' && user.role !== 'viewer' && <button className="approve" onClick={() => approve(live.id)}>Approve</button>}</div>{index < selectedSteps.length - 1 && <div className="connector" />}</div>})}</div></> : <div className="empty">Choose a workflow from the list to inspect its execution graph.</div>}</section></div>
      {runId && <section className="panel run-panel"><div className="panel-heading"><div><p className="eyebrow">Observability / {runId.slice(0, 8)}</p><h2>Live run timeline</h2></div><span className={`badge ${activeRunStatus}`}><span className="status-pulse" /> {activeRunStatus}</span></div><div className="timeline">{stepRuns.map((step) => <div className="timeline-item" key={step.id}><span className={`timeline-dot ${step.status}`} /><div><strong>Step {step.workflow_step?.step_order}: {step.workflow_step?.step_type}</strong><small>{step.error || (step.output ? JSON.stringify(step.output).slice(0, 120) : 'Waiting for execution')}</small></div><span className="timeline-time">{step.status}</span></div>)}</div></section>}
      <footer><span>SubSpace Workflow Platform</span><span>Role-aware execution · quota protected · audit ready</span></footer>
    </section>
  </div></main>
}
